# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created: Mon Jun 03 12:55:16 2013
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1000, 800)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_9 = QtGui.QWidget()
        self.tab_9.setObjectName(_fromUtf8("tab_9"))
        self.layoutWidget = QtGui.QWidget(self.tab_9)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1011, 761))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.scrollArea = QtGui.QScrollArea(self.layoutWidget)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 978, 778))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.frameUserControls = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frameUserControls.setGeometry(QtCore.QRect(0, 380, 981, 401))
        self.frameUserControls.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frameUserControls.setFrameShadow(QtGui.QFrame.Raised)
        self.frameUserControls.setObjectName(_fromUtf8("frameUserControls"))
        self.frameLoadSaveControls = QtGui.QFrame(self.frameUserControls)
        self.frameLoadSaveControls.setGeometry(QtCore.QRect(660, 0, 311, 321))
        self.frameLoadSaveControls.setFrameShape(QtGui.QFrame.Panel)
        self.frameLoadSaveControls.setFrameShadow(QtGui.QFrame.Plain)
        self.frameLoadSaveControls.setObjectName(_fromUtf8("frameLoadSaveControls"))
        self.pushButtonChooseSaveFile = QtGui.QPushButton(self.frameLoadSaveControls)
        self.pushButtonChooseSaveFile.setEnabled(True)
        self.pushButtonChooseSaveFile.setGeometry(QtCore.QRect(150, 190, 91, 21))
        self.pushButtonChooseSaveFile.setText(QtGui.QApplication.translate("MainWindow", "Choose File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChooseSaveFile.setObjectName(_fromUtf8("pushButtonChooseSaveFile"))
        self.textEditSaveStatus = QtGui.QTextEdit(self.frameLoadSaveControls)
        self.textEditSaveStatus.setGeometry(QtCore.QRect(20, 280, 221, 31))
        self.textEditSaveStatus.setReadOnly(True)
        self.textEditSaveStatus.setObjectName(_fromUtf8("textEditSaveStatus"))
        self.pushButtonSavePS = QtGui.QPushButton(self.frameLoadSaveControls)
        self.pushButtonSavePS.setGeometry(QtCore.QRect(30, 220, 211, 31))
        self.pushButtonSavePS.setText(QtGui.QApplication.translate("MainWindow", "Save Pulse Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSavePS.setObjectName(_fromUtf8("pushButtonSavePS"))
        self.label_12 = QtGui.QLabel(self.frameLoadSaveControls)
        self.label_12.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Load Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.textEditSaveFile = QtGui.QTextEdit(self.frameLoadSaveControls)
        self.textEditSaveFile.setGeometry(QtCore.QRect(20, 190, 111, 21))
        self.textEditSaveFile.setObjectName(_fromUtf8("textEditSaveFile"))
        self.label_10 = QtGui.QLabel(self.frameLoadSaveControls)
        self.label_10.setGeometry(QtCore.QRect(10, 260, 61, 16))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Save Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.textEditLoadStatus = QtGui.QTextEdit(self.frameLoadSaveControls)
        self.textEditLoadStatus.setGeometry(QtCore.QRect(30, 120, 211, 31))
        self.textEditLoadStatus.setReadOnly(True)
        self.textEditLoadStatus.setObjectName(_fromUtf8("textEditLoadStatus"))
        self.label_9 = QtGui.QLabel(self.frameLoadSaveControls)
        self.label_9.setGeometry(QtCore.QRect(10, 170, 46, 13))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Save File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.pushButtonLoadPS = QtGui.QPushButton(self.frameLoadSaveControls)
        self.pushButtonLoadPS.setGeometry(QtCore.QRect(30, 60, 211, 31))
        self.pushButtonLoadPS.setText(QtGui.QApplication.translate("MainWindow", "Load Pulse Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLoadPS.setObjectName(_fromUtf8("pushButtonLoadPS"))
        self.label_11 = QtGui.QLabel(self.frameLoadSaveControls)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Load File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.textEditLoadFile = QtGui.QTextEdit(self.frameLoadSaveControls)
        self.textEditLoadFile.setGeometry(QtCore.QRect(20, 30, 111, 21))
        self.textEditLoadFile.setObjectName(_fromUtf8("textEditLoadFile"))
        self.pushButtonChooseLoadFile = QtGui.QPushButton(self.frameLoadSaveControls)
        self.pushButtonChooseLoadFile.setGeometry(QtCore.QRect(150, 30, 91, 21))
        self.pushButtonChooseLoadFile.setText(QtGui.QApplication.translate("MainWindow", "Choose File", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonChooseLoadFile.setObjectName(_fromUtf8("pushButtonChooseLoadFile"))
        self.framePulseSequenceControls = QtGui.QFrame(self.frameUserControls)
        self.framePulseSequenceControls.setGeometry(QtCore.QRect(0, 0, 661, 321))
        self.framePulseSequenceControls.setFrameShape(QtGui.QFrame.Panel)
        self.framePulseSequenceControls.setFrameShadow(QtGui.QFrame.Plain)
        self.framePulseSequenceControls.setLineWidth(2)
        self.framePulseSequenceControls.setObjectName(_fromUtf8("framePulseSequenceControls"))
        self.label_7 = QtGui.QLabel(self.framePulseSequenceControls)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Channel Number", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.framePulseTrainControls = QtGui.QFrame(self.framePulseSequenceControls)
        self.framePulseTrainControls.setGeometry(QtCore.QRect(10, 60, 621, 251))
        self.framePulseTrainControls.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.framePulseTrainControls.setFrameShape(QtGui.QFrame.Panel)
        self.framePulseTrainControls.setFrameShadow(QtGui.QFrame.Plain)
        self.framePulseTrainControls.setLineWidth(1)
        self.framePulseTrainControls.setObjectName(_fromUtf8("framePulseTrainControls"))
        self.label_4 = QtGui.QLabel(self.framePulseTrainControls)
        self.label_4.setGeometry(QtCore.QRect(10, 12, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Pulse Train Index", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEditTimeOn = QtGui.QLineEdit(self.framePulseTrainControls)
        self.lineEditTimeOn.setGeometry(QtCore.QRect(10, 70, 101, 20))
        self.lineEditTimeOn.setObjectName(_fromUtf8("lineEditTimeOn"))
        self.pushButtonDeletePulse = QtGui.QPushButton(self.framePulseTrainControls)
        self.pushButtonDeletePulse.setGeometry(QtCore.QRect(320, 100, 271, 31))
        self.pushButtonDeletePulse.setText(QtGui.QApplication.translate("MainWindow", "Delete Pulse", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDeletePulse.setObjectName(_fromUtf8("pushButtonDeletePulse"))
        self.label = QtGui.QLabel(self.framePulseTrainControls)
        self.label.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Time On (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_6 = QtGui.QLabel(self.framePulseTrainControls)
        self.label_6.setGeometry(QtCore.QRect(320, 50, 101, 16))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Pulse Separation (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEditPulseSeparation = QtGui.QLineEdit(self.framePulseTrainControls)
        self.lineEditPulseSeparation.setGeometry(QtCore.QRect(320, 70, 111, 20))
        self.lineEditPulseSeparation.setObjectName(_fromUtf8("lineEditPulseSeparation"))
        self.lineEditPulseWidth = QtGui.QLineEdit(self.framePulseTrainControls)
        self.lineEditPulseWidth.setGeometry(QtCore.QRect(160, 70, 111, 20))
        self.lineEditPulseWidth.setObjectName(_fromUtf8("lineEditPulseWidth"))
        self.pushButtonAddPulse = QtGui.QPushButton(self.framePulseTrainControls)
        self.pushButtonAddPulse.setGeometry(QtCore.QRect(10, 100, 261, 31))
        self.pushButtonAddPulse.setText(QtGui.QApplication.translate("MainWindow", "Add Pulse", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddPulse.setObjectName(_fromUtf8("pushButtonAddPulse"))
        self.label_3 = QtGui.QLabel(self.framePulseTrainControls)
        self.label_3.setGeometry(QtCore.QRect(480, 50, 91, 16))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Pulses in Train", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.framePulseTrainControls)
        self.label_2.setGeometry(QtCore.QRect(160, 50, 81, 16))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Pulse Width (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBoxPulseTrainIndex = QtGui.QComboBox(self.framePulseTrainControls)
        self.comboBoxPulseTrainIndex.setGeometry(QtCore.QRect(150, 12, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxPulseTrainIndex.setFont(font)
        self.comboBoxPulseTrainIndex.setObjectName(_fromUtf8("comboBoxPulseTrainIndex"))
        self.lineEditPulsesInTrain = QtGui.QLineEdit(self.framePulseTrainControls)
        self.lineEditPulsesInTrain.setGeometry(QtCore.QRect(480, 72, 113, 20))
        self.lineEditPulsesInTrain.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditPulsesInTrain.setInputMask(_fromUtf8(""))
        self.lineEditPulsesInTrain.setObjectName(_fromUtf8("lineEditPulsesInTrain"))
        self.label_16 = QtGui.QLabel(self.framePulseTrainControls)
        self.label_16.setGeometry(QtCore.QRect(10, 160, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Wait Events Index", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEditWaitTime = QtGui.QLineEdit(self.framePulseTrainControls)
        self.lineEditWaitTime.setGeometry(QtCore.QRect(80, 210, 113, 20))
        self.lineEditWaitTime.setObjectName(_fromUtf8("lineEditWaitTime"))
        self.label_17 = QtGui.QLabel(self.framePulseTrainControls)
        self.label_17.setGeometry(QtCore.QRect(40, 210, 46, 13))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.pushButtonAddWait = QtGui.QPushButton(self.framePulseTrainControls)
        self.pushButtonAddWait.setGeometry(QtCore.QRect(230, 200, 141, 31))
        self.pushButtonAddWait.setText(QtGui.QApplication.translate("MainWindow", "Add Wait Event", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddWait.setObjectName(_fromUtf8("pushButtonAddWait"))
        self.pushButtonDeleteWait = QtGui.QPushButton(self.framePulseTrainControls)
        self.pushButtonDeleteWait.setGeometry(QtCore.QRect(400, 200, 141, 31))
        self.pushButtonDeleteWait.setText(QtGui.QApplication.translate("MainWindow", "Delete Wait Event", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDeleteWait.setObjectName(_fromUtf8("pushButtonDeleteWait"))
        self.comboBoxWaitEvents = QtGui.QComboBox(self.framePulseTrainControls)
        self.comboBoxWaitEvents.setGeometry(QtCore.QRect(150, 160, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxWaitEvents.setFont(font)
        self.comboBoxWaitEvents.setObjectName(_fromUtf8("comboBoxWaitEvents"))
        self.label_18 = QtGui.QLabel(self.framePulseTrainControls)
        self.label_18.setGeometry(QtCore.QRect(360, 170, 131, 20))
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "Begin loop after first wait?", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.checkBoxWaitLoop = QtGui.QCheckBox(self.framePulseTrainControls)
        self.checkBoxWaitLoop.setGeometry(QtCore.QRect(490, 170, 16, 17))
        self.checkBoxWaitLoop.setText(_fromUtf8(""))
        self.checkBoxWaitLoop.setObjectName(_fromUtf8("checkBoxWaitLoop"))
        self.comboBoxChannel = QtGui.QComboBox(self.framePulseSequenceControls)
        self.comboBoxChannel.setGeometry(QtCore.QRect(160, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comboBoxChannel.setFont(font)
        self.comboBoxChannel.setObjectName(_fromUtf8("comboBoxChannel"))
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 971, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Pulse Sequence Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setIndent(0)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.widgetMPLPlot = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widgetMPLPlot.setEnabled(True)
        self.widgetMPLPlot.setGeometry(QtCore.QRect(0, 40, 971, 301))
        self.widgetMPLPlot.setObjectName(_fromUtf8("widgetMPLPlot"))
        self.mplwidgetPulseSeq = MatplotlibWidget(self.widgetMPLPlot)
        self.mplwidgetPulseSeq.setGeometry(QtCore.QRect(260, 10, 251, 251))
        self.mplwidgetPulseSeq.setObjectName(_fromUtf8("mplwidgetPulseSeq"))
        self.widgetMPLToolbar = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.widgetMPLToolbar.setGeometry(QtCore.QRect(-1, 330, 971, 51))
        self.widgetMPLToolbar.setObjectName(_fromUtf8("widgetMPLToolbar"))
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_9, _fromUtf8(""))
        self.tab_10 = QtGui.QWidget()
        self.tab_10.setObjectName(_fromUtf8("tab_10"))
        self.textEditMessages = QtGui.QTextEdit(self.tab_10)
        self.textEditMessages.setGeometry(QtCore.QRect(13, 40, 891, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEditMessages.setFont(font)
        self.textEditMessages.setReadOnly(True)
        self.textEditMessages.setObjectName(_fromUtf8("textEditMessages"))
        self.frame = QtGui.QFrame(self.tab_10)
        self.frame.setGeometry(QtCore.QRect(10, 330, 781, 161))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.pushButtonStartSequence = QtGui.QPushButton(self.frame)
        self.pushButtonStartSequence.setGeometry(QtCore.QRect(440, 100, 201, 41))
        self.pushButtonStartSequence.setText(QtGui.QApplication.translate("MainWindow", "Start Pulse Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStartSequence.setAutoDefault(False)
        self.pushButtonStartSequence.setDefault(False)
        self.pushButtonStartSequence.setFlat(False)
        self.pushButtonStartSequence.setObjectName(_fromUtf8("pushButtonStartSequence"))
        self.pushButtonInitializePB = QtGui.QPushButton(self.frame)
        self.pushButtonInitializePB.setGeometry(QtCore.QRect(440, 30, 201, 41))
        self.pushButtonInitializePB.setText(QtGui.QApplication.translate("MainWindow", "Test Initialization", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonInitializePB.setObjectName(_fromUtf8("pushButtonInitializePB"))
        self.lineEditPBClockFrequency = QtGui.QLineEdit(self.frame)
        self.lineEditPBClockFrequency.setGeometry(QtCore.QRect(10, 30, 271, 20))
        self.lineEditPBClockFrequency.setText(QtGui.QApplication.translate("MainWindow", "400.0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditPBClockFrequency.setObjectName(_fromUtf8("lineEditPBClockFrequency"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 221, 16))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "PB Clock Speed (MHz) [Determined by Board]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.checkBoxInfiniteLoop = QtGui.QCheckBox(self.frame)
        self.checkBoxInfiniteLoop.setGeometry(QtCore.QRect(10, 80, 81, 20))
        self.checkBoxInfiniteLoop.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBoxInfiniteLoop.setText(QtGui.QApplication.translate("MainWindow", "Infinite Loop", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxInfiniteLoop.setObjectName(_fromUtf8("checkBoxInfiniteLoop"))
        self.spinBoxNumberOfLoops = QtGui.QSpinBox(self.frame)
        self.spinBoxNumberOfLoops.setGeometry(QtCore.QRect(100, 130, 181, 22))
        self.spinBoxNumberOfLoops.setMinimum(1)
        self.spinBoxNumberOfLoops.setMaximum(1048576)
        self.spinBoxNumberOfLoops.setObjectName(_fromUtf8("spinBoxNumberOfLoops"))
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(10, 130, 91, 16))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Number of Loops", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.doubleSpinBoxRunTime = QtGui.QDoubleSpinBox(self.frame)
        self.doubleSpinBoxRunTime.setGeometry(QtCore.QRect(180, 80, 101, 22))
        self.doubleSpinBoxRunTime.setDecimals(6)
        self.doubleSpinBoxRunTime.setMinimum(1e-06)
        self.doubleSpinBoxRunTime.setMaximum(1000000000.0)
        self.doubleSpinBoxRunTime.setProperty("value", 10.0)
        self.doubleSpinBoxRunTime.setObjectName(_fromUtf8("doubleSpinBoxRunTime"))
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(110, 80, 71, 16))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Run Time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.pushButtonClearMessages = QtGui.QPushButton(self.tab_10)
        self.pushButtonClearMessages.setGeometry(QtCore.QRect(810, 330, 91, 23))
        self.pushButtonClearMessages.setText(QtGui.QApplication.translate("MainWindow", "Clear Messages", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClearMessages.setObjectName(_fromUtf8("pushButtonClearMessages"))
        self.label_13 = QtGui.QLabel(self.tab_10)
        self.label_13.setGeometry(QtCore.QRect(20, 20, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Messages from subprocess", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.tabWidget.addTab(self.tab_10, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), QtGui.QApplication.translate("MainWindow", "Pulse Sequence Generator", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), QtGui.QApplication.translate("MainWindow", "Pulse Blaster Controls", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
